  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_arm
    pid: {p: 150, i: 0.001, d: 0.001}
    
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_arm
    pid: {p: 150, i: 0.001, d: 0.001}
    
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_arm1
    pid: {p: 8, i: 0.001, d: 0.001}
    
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_arm2
    pid: {p: 5, i: 0.001, d: 0.001}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_arm3
    pid: {p: 1, i: 0.001, d: 0.001}
    
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_arm1
    pid: {p: 100, i: 0.001, d: 0.001}
    
 
    


    
  



